"""empty message

Revision ID: cd53db95c952
Revises: ea17067a84ed
Create Date: 2023-01-21 22:25:56.244032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd53db95c952'
down_revision = 'ea17067a84ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
