"""empty message

Revision ID: de2ddba149af
Revises: 625b1e2f13cf
Create Date: 2023-01-21 22:33:04.534176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2ddba149af'
down_revision = '625b1e2f13cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
