version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app :/app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql://user:password@db/dbname
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
