version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app :/app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql://user:dbadmin@db/dbadmin
    stdin_open: true
    tty: true
    networks:
      - fastapi_network
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbadmin
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - fastapi_network
